apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hello-backend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: {{ .Release.Name }}-hello-backend
