apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-profile-backend
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: {{ .Release.Name }}-profile-backend
